### PR TITLE
Note that post mideterm topics have more weight on the final

### PR DESCRIPTION
**Pull request by joelostblom**
**Don't merge until after noon on Friday**

I think we should indicate that post-midterm topics make up a bigger part of the final. I received a question about this just a few days before the final and noticed that we didn't mention it anywhere in the syllabus. At this point I think it would not be fair to answer just one student since not all students would be able to see that info before the final.

### CODE REVIEW

**Comment by trevorcampbell** [comment]
@joelostblom we definitely dont want to lock ourselves into a decision like this. The issue is in some future year when it's about even split, some students will complain that we lied to them (because we forgot this was in the syllabus)

**Comment by joelostblom** [comment]
I see, but wouldn't we want to have an explicit internal and external policy on the weighting? That we intend for the midterm to be more heavily weighted toward the post-midterm topics unless there is a significant course restructuring and we move away from the two exam format? In which case we would need to update the final anyways (like we did when transitioning from three quizzes to two exams).

**Comment by trevorcampbell** [comment]
No -- there isn't any point in locking ourselves into strict policies like that (that we are then beholden to). The benefit to students is negligible -- they should already be aware that the final covers all material in the class. The potential downside could be major -- someone lodging a complaint that we didn't follow our own syllabus.

(In practice yes the final will naturally have a bit more 2nd half material, but no reason to have any policy -- external or internal -- on it)

**Comment by joelostblom** [comment]
Ok, I'm closing this then!

**Pull request closed without merging**
