### PR TITLE
Add python reference sheet

### PR DESCRIPTION
**Pull request by joelostblom**
This is my suggestion for what the reference sheet can look like. Let me know your thoughts @trevorcampbell and @chendaniely .

### CODE REVIEW

**Review by trevorcampbell — COMMENTED** [review]
Thanks for the PR @joelostblom . I don't think this quite hits what I would want from the cheat sheet. In particular,
- I don't want example usage in a script that is representative of questions we will ask, like what is shown here. Especially not the stuff where you show the full pipeline of tuning a model. This will prompt copy-pasting from the sheet, and will mean that students don't need to remember what order to do things in, which is really what we are trying to avoid by going closed-book.
- I also don't want the sheet to include an explanation of what the function does -- that's just noise they have to sift through (and we may ask questions about functions whose answers become obvious given this)
- I would want to include names of arguments in functions (the ones we use in the course, anyway, not all arguments) as well as a brief description of what they are

So I would expect something more basic, just like the following:
- `function(arg1, arg2, arg3)`
  - `arg1` is a scalar
  - `arg2` is a data frame
  - `arg3` is a scalar

where `function` and `arg1` etc of course have more obvious names, like `kmeans(n_clusters, n_starts)`  

Thoughts? In my mind, the cheat sheet is just there to solve the "crap what order were the arguments in? what were the names of those arguments? i can't remember" problem

**Comment by joelostblom** [comment]
Thanks for having a look! It sounds like this sheet is too heavy on the cheat side of things. I agree that the scikit-learn sample might be a bit much since it gives a way important information about the order of operations which in that case is more than just learning syntax. For altair and pandas I find it is more acceptable, but I think I'm ok with leaving that out too... or maybe creating a much more basic example for each? For example, the altair example could be shortened to:

```python
alt.Chart(df).mark_point().encode(
    x='column1',
    y=alt.Y('column2').title('Column 2')
)
```

and the pandas one:

```python
df.loc[
    df['column2'] < 10,
    ['column2', 'column3']
]
```

and then for sklearn:

```python
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)
```

I do think the function description could be helpful and still fair to include. I think it is OK if they are able to recall what a function does and how to use it based on that short description. From the year I taught DSCI 100 in R, I am not expecting us to ask any questions along the line of "what does function X do", but maybe that is not exactly what you mean?

I'm actually hesitant to include all the parameter names and types; that sounds tedious to type out and also maybe too helpful is some cases? I'm probably OK with including it, mostly hesitant about typing it. Would it look like this `read_csv(filepath: str, sep: str, names: list|dict)` and `mark_line(point: bool)` and `GridSearchCV(estimator: sklearn.estimator, param_grid: dict, cv: int)`?

**Comment by trevorcampbell** [comment]
I'm OK with those much-shortened examples you gave.

> I do think the function description could be helpful and still fair to include. I think it is OK if they are able to recall what a function does and how to use it based on that short description.

I'm still on the fence about these short descriptions, but you can test-run including them this semester if you want and we'll see how it goes.

> I'm actually hesitant to include all the parameter names and types; that sounds tedious to type out and also maybe too helpful is some cases? I'm probably OK with including it, mostly hesitant about typing it. Would it look like this read_csv(filepath: str, sep: str, names: list|dict) and mark_line(point: bool) and GridSearchCV(estimator: sklearn.estimator, param_grid: dict, cv: int)?

I think the two examples you give here are precisely what we're looking for -- just a reminder of the syntax of calling a function, with argument names and types (maybe the types can be omitted as long as the argument names make it clear what they are). It will be a bit of work, but I think this is a short-term cost for long-term win, and maintaining it once it's set won't be too much work. My primary concern would be if it causes a lot of ongoing maintenance, but I think in this case it won't.

**Comment by joelostblom** [comment]
@trevorcampbell I had a go at it in my latest commit, went quicker then I thought to put together this first draft. Have a look.

I am uncertain in some cases where the name of the parameter is either not that useful, or something we don't use in DSCI 100 because we rely on the order instead. For example, should we type `groupby(by)` although we never use it as `groupby(by='column')`, but rather always use `groupby('column')`. Maybe `groupby('column')` is more useful or even just `groupby()`? Here are a few more examples where the first one is the actual param name and the remaining rows something potentially more useful:

```
merge(right, on)
merge(df, on)

DataFrame(data)
DataFrame(dict)

agg(func)
agg(['...', '...'])

contains(pat)
contains('string_to_match')

make_column_transformer(transformers)
make_column_transformer((operation, list_of_columns))
make_column_transformer((operation, ['col1', 'col2']))
```

**Comment by trevorcampbell** [comment]
@joelostblom I agree that the "more useful" option is the right one to go with. We aren't writing precise documentation here -- we're trying to give students a way to jog their memory on stupid syntax that nobody should have to memorize. So having
```
merge(right, on)
```
is not the right approach, because it'll likely just confuse students (what is `right`?) even if it does match the pandas docs. Instead,
```
merge(df, on)
```
is more likely to jog their memory

**Comment by joelostblom** [comment]
Thanks @trevorcampbell , I updated to follow that pattern throughout; ready for a review again.

**Review by trevorcampbell — APPROVED** [review]
This looks great to me. I did not check how comprehensive it is -- I assume you've included everything necessary -- but what is there is good!

**Comment by joelostblom** [comment]
I added a short note in the readme to link this page so that it is included in the built website

**Pull request merged**
